/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 AATRLBLZRS GLTF.glb --transform --output aatrlblzrs.jsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
  };
  materials: {};
};

export function AATraillBlazersModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/AATRLBLZRS GLTF-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <ambientLight position={[10, 10, 5]} intensity={2} castShadow />
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  );
}

useGLTF.preload('/AATRLBLZRS GLTF-transformed.glb')
