/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 AATRLBLZRS GLTF.glb --transform --output aatrlblzrs.jsx
*/

import React, { useRef } from 'react'
import { useGLTF, FlyControls } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export function AATraillBlazersModel(props) {
  const { nodes, materials } = useGLTF('/AATRLBLZRS GLTF-transformed.glb')
  const { scene, camera } = useThree()
  return (
    <group {...props} dispose={null}>
      <ambientLight position={[10, 10, 5]} intensity={2} castShadow />
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/AATRLBLZRS GLTF-transformed.glb')
