/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/williamkrakow/Desktop/GOURMET KINGDOM.glb --types --transform
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
  };
  materials: {};
};

export function GourmetKingdomModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/GOURMET KINGDOM-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <ambientLight position={[10, 10, 5]} intensity={2} castShadow />
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  );
}

useGLTF.preload("/GOURMET KINGDOM-transformed.glb");
