/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 HopeGLTF.glb --transform --output hope.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HopeModel(props) {
  const { nodes, materials } = useGLTF('/HopeGLTF-transformed.glb')
  
  return (
    <group {...props} dispose={null}>
      <ambientLight position={[10, 10, 5]} intensity={2} castShadow />
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/HopeGLTF-transformed.glb')
