/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./PRTRT.glb --transform --types --shadows --keepgroups --precision 4
*/

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {}
}

export function PortraitModel(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/PRTRT.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <ambientLight intensity={0.9} castShadow position={[10, -10, 5]} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/PRTRT.glb')
