/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 TOPO GLTF.glb --transform --output topo.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TOPOModel(props) {
  const { nodes, materials, scene, cameras } = useGLTF('/TOPO GLTF-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <ambientLight position={[10, 10, 5]} intensity={2} castShadow />
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/TOPO GLTF-transformed.glb')
